name: masonry
channels:
  - conda-forge
dependencies:
  - pip
  - python
  - compas
  - compas_occ
  - ipopt
  - numpy <2.0
  - pyomo ==6.4.2
  - cyipopt
  - pip:
      - -r requirements-dev.txt
      - -r requirements-viz.txt
      - -r requirements.txt
