#! python3
# venv: brg-csd
# r: compas_masonry>=0.2.7

"""Problem_boundaryconditions — prescribed displacements / rotations on a Problem.

Fixed supports live at the MODEL stage (Model_supports -> Block.is_support, then
inherited by Problem_create via add_supports_from_model). This command handles
*prescribed* (non-zero) displacement and rotation boundary conditions only.

Flow: pick a problem -> Add / Remove -> Displacement / Rotation -> select blocks
-> vector. Geometry is regenerated by session.draw_problem() under the problem's
"Boundary conditions" layers.
"""

import pathlib

import rhinoscriptsyntax as rs  # type: ignore

import compas_rhino.objects
from compas_dem.models import BlockModel
from compas_masonry.session import MasonrySession as Session
from compas_rui.feedback import warn


def selected_nodes(session, model, message):
    guids = compas_rhino.objects.select_objects(message=message)
    if not guids:
        return []
    guid_element_map = session.guid_element_map(model)
    return sorted({n for n in (session.find_node(g, guid_element_map) for g in guids) if n is not None})


def get_vector(prompt, dz=0.0):
    x = rs.GetReal(f"{prompt} x", 0.0)
    if x is None:
        return None
    y = rs.GetReal(f"{prompt} y", 0.0)
    if y is None:
        return None
    z = rs.GetReal(f"{prompt} z", dz)
    if z is None:
        return None
    return [x, y, z]


def is_support(entry):
    return entry.get("translation") == [0.0, 0.0, 0.0] and entry.get("rotation") == [0.0, 0.0, 0.0]


def add_bc(session, problem, model):
    kind = rs.GetString(message="BC type", strings=["Displacement", "Rotation"])
    if not kind:
        return
    nodes = selected_nodes(session, model, f"Select blocks for the {kind.lower()}")
    if not nodes:
        return

    if kind == "Displacement":
        vec = get_vector("Displacement [m]")
        if vec is None:
            return
        for node in nodes:
            problem.add_displacement(node, displacement=vec)
        print(f"Added displacement {vec} to {len(nodes)} block(s).")
    else:
        vec = get_vector("Rotation [rad]")
        if vec is None:
            return
        for node in nodes:
            problem.add_rotation(node, vec)
        print(f"Added rotation {vec} to {len(nodes)} block(s).")


def remove_bc(problem):
    # Only prescribed (non-support) displacement/rotation entries are removable here.
    displacements = problem.boundary_conditions.displacements
    removable = [(i, e) for i, e in enumerate(displacements) if not is_support(e)]
    if not removable:
        return warn("No prescribed displacements/rotations to remove (supports are managed in Model_supports).")
    for listpos, (i, e) in enumerate(removable):
        print(f"{listpos}: block {e['block_index']} translation={e['translation']} rotation={e['rotation']}")
    pick = rs.GetString(message="Entry index to remove", strings=[str(i) for i in range(len(removable))])
    if not pick:
        return
    original_index = removable[int(pick)][0]
    removed = displacements.pop(original_index)
    print(f"Removed BC: {removed}")


def RunCommand():
    session = Session(basedir=pathlib.Path().home() / ".compas_session", name="COMPAS-Masonry")

    model: BlockModel = session.get("blockmodel")
    if model is None:
        return warn("No existing BlockModel in session. Please create one first.")
    if not session.problems:
        return warn("No problem in session. Run Problem_create first.")

    name = session.choose_problem(message="Problem to edit BCs on")
    if name is None:
        return
    problem = session.problems[name]

    option = rs.GetString(message="Boundary conditions", strings=["Add", "Remove"])
    if not option:
        return

    if option == "Add":
        add_bc(session, problem, model)
    elif option == "Remove":
        remove_bc(problem)

    session.save_problems()
    session.draw_problem(name, model)


# =============================================================================
# Run as main
# =============================================================================

if __name__ == "__main__":
    RunCommand()
